services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: chrome_xvfb
    user: root
    volumes:
      - ./:/opt/app
    working_dir: /opt/app/src
    command: bash -c "xvfb-run --auto-servernum --server-args='-screen 0, 1024x768x24' -- python mf2gs.py > /dev/null"